name = "hiddencameras-tv"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_AMAZON_TAG = "hiddencamerastv-20"
NEXT_PUBLIC_ENABLE_AD_UNITS = "true"
