// Curated Fashionistas.ai camera catalog for hiddencameras.tv editor roundups.
// Hard-coded at build time to keep pages static and avoid runtime fetch flake.
// Source: Shopify Admin GraphQL on js0hy0-ux, collection security-cameras,
// filtered to legitimate cameras (no phone-case/drone/toy junk).
// Refreshed 2026-04-21.

const PRODUCTS = {
  "4k-mini-wifi-pinhole-hidden-camera": {
    handle: "4k-mini-wifi-pinhole-hidden-camera",
    title: "4K Mini WiFi Pinhole Hidden Camera",
    price: "54.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/93a5ffe849d2bc14650bf077d71f_import.webp?v=1776700498",
    category: "hidden",
  },
  "pocket-pen-hd-hidden-camera": {
    handle: "pocket-pen-hd-hidden-camera",
    title: "Pocket Pen HD Hidden Camera",
    price: "49.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/73ddcaa94451a2829137b4c3e919_import.webp?v=1776700507",
    category: "hidden",
  },
  "mini-hidden-nanny-cam-1080p": {
    handle: "mini-hidden-nanny-cam-1080p",
    title: "Mini Hidden Nanny Cam 1080p",
    price: "44.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/f87678c148429c744b40c5316309_import.webp?v=1776700515",
    category: "hidden",
  },
  "night-vision-1080p-resolution-portable-mini-camera-1025333310": {
    handle: "night-vision-1080p-resolution-portable-mini-camera-1025333310",
    title: "Night Vision 1080p Portable Mini Camera",
    price: "18.67",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/product-image-590255746.jpg?v=1734006412",
    category: "hidden",
  },
  "dice-style-hidden-nanny-cam-1080p": {
    handle: "dice-style-hidden-nanny-cam-1080p",
    title: "Dice-Style Hidden Nanny Cam 1080p",
    price: "44.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/1058b59d4d83976d2d391f5ce4e9_import.webp?v=1776700623",
    category: "nanny",
  },
  "mini-wireless-wifi-nanny-cam-palm-size": {
    handle: "mini-wireless-wifi-nanny-cam-palm-size",
    title: "Mini Wireless WiFi Nanny Cam - Palm-Size",
    price: "34.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/20201553475987c99b7da96f6b22_import.webp?v=1776700615",
    category: "nanny",
  },
  "amcrest-1080p-nanny-pet-wifi-camera": {
    handle: "amcrest-1080p-nanny-pet-wifi-camera",
    title: "Amcrest 1080p Nanny + Pet WiFi Camera",
    price: "69.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/2864e26446f7b0ee460f2ed39a88_import.webp?v=1776700606",
    category: "nanny",
  },
  "wireless-1080p-indoor-security-camera": {
    handle: "wireless-1080p-indoor-security-camera",
    title: "Wireless 1080p Indoor Security Camera",
    price: "29.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/ce4a354e401f9f52a0a205019565_import.webp?v=1776700523",
    category: "indoor",
  },
  "1080p-pan-tilt-zoom-indoor-pet-baby-monitor": {
    handle: "1080p-pan-tilt-zoom-indoor-pet-baby-monitor",
    title: "1080p Pan-Tilt-Zoom Indoor Pet/Baby Monitor",
    price: "49.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/1cf02a014b8ca066842f08540aea_import.webp?v=1776700530",
    category: "indoor",
  },
  "2k-pan-tilt-pet-baby-camera-with-smart-tracking": {
    handle: "2k-pan-tilt-pet-baby-camera-with-smart-tracking",
    title: "2K Pan-Tilt Pet + Baby Camera with Smart Tracking",
    price: "79.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/88e9158a41d48aaabb05efcc5bae_import.webp?v=1776700536",
    category: "indoor",
  },
  "ip65-outdoor-wifi-camera-v380-pro": {
    handle: "ip65-outdoor-wifi-camera-v380-pro",
    title: "IP65 Outdoor WiFi Camera V380 Pro",
    price: "34.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/25d7661a4daab3d111e99415baa8_import.webp?v=1776700543",
    category: "outdoor",
  },
  "1080p-ip66-outdoor-wifi-bullet-camera": {
    handle: "1080p-ip66-outdoor-wifi-bullet-camera",
    title: "1080p IP66 Outdoor WiFi Bullet Camera",
    price: "54.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/9c1a00b04a4ab270d65f34493fae_import.webp?v=1776700550",
    category: "outdoor",
  },
  "solar-powered-outdoor-wifi-camera-with-night-vision": {
    handle: "solar-powered-outdoor-wifi-camera-with-night-vision",
    title: "Solar-Powered Outdoor WiFi Camera with Night Vision",
    price: "39.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/cc532fe94fda8e1846699ae909b1_import.webp?v=1776700557",
    category: "outdoor",
  },
  "wifi-surveillance-camera-4k-8mp-dual-lens-wireless-outdoor-security-ptz-ip-cameras-ai-human-detect-cctv-camera-4x-digital-zoom": {
    handle: "wifi-surveillance-camera-4k-8mp-dual-lens-wireless-outdoor-security-ptz-ip-cameras-ai-human-detect-cctv-camera-4x-digital-zoom",
    title: "4K 8MP Dual-Lens Outdoor PTZ IP Camera",
    price: "21.00",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/ffd44bafc4fb41de8364954ef7578850.webp?v=1733831231",
    category: "outdoor",
  },
  "battery-powered-wifi-video-doorbell": {
    handle: "battery-powered-wifi-video-doorbell",
    title: "Battery-Powered WiFi Video Doorbell",
    price: "29.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/825cd4634a6383eb81a190c7d84e_import.webp?v=1776700566",
    category: "doorbell",
  },
  "smart-wifi-video-doorbell-m7-with-remote-monitoring": {
    handle: "smart-wifi-video-doorbell-m7-with-remote-monitoring",
    title: "Smart WiFi Video Doorbell M7 with Remote Monitoring",
    price: "44.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/c5e1ea364c7daba35dd2d67f393e_import.webp?v=1776700575",
    category: "doorbell",
  },
  "smart-wireless-video-doorbell-with-night-vision": {
    handle: "smart-wireless-video-doorbell-with-night-vision",
    title: "Smart Wireless Video Doorbell with Night Vision",
    price: "59.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/b52820bc443d8be8777cda304f45_import.webp?v=1776700581",
    category: "doorbell",
  },
  "wireless-wifi-video-doorbell-with-music-bell-full-hd-resolution-two-1508265658": {
    handle: "wireless-wifi-video-doorbell-with-music-bell-full-hd-resolution-two-1508265658",
    title: "Wireless WiFi Video Doorbell with Music Bell",
    price: "51.59",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/getpubthumb_08aad9d8-fd8f-466f-8030-9ca1b7c1b359.jpg?v=1734006418",
    category: "doorbell",
  },
  "dual-lens-b6t-dashcam-12mp-170-view": {
    handle: "dual-lens-b6t-dashcam-12mp-170-view",
    title: "Dual-Lens B6T Dashcam 12MP, 170 Degree View",
    price: "39.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/01327f884d96beac832ef6523189_import.webp?v=1776700587",
    category: "dash",
  },
  "4-inch-ips-dual-channel-starlight-night-vision-dashcam": {
    handle: "4-inch-ips-dual-channel-starlight-night-vision-dashcam",
    title: "4-Inch IPS Dual-Channel Starlight Night-Vision Dashcam",
    price: "44.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/1aa432b74625901c07802f039c0b_import.webp?v=1776700594",
    category: "dash",
  },
  "1080p-touch-screen-dashcam-with-carplay": {
    handle: "1080p-touch-screen-dashcam-with-carplay",
    title: "1080p Touch-Screen Dashcam with CarPlay",
    price: "64.99",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/6a9cd49646faa07ab88321c1cea8_import.webp?v=1776700600",
    category: "dash",
  },
  "2-4-inch-full-hd-1080p-dash-cam-car-dvr-front-camera-or-rear-camera-night-vision-g-sensor": {
    handle: "2-4-inch-full-hd-1080p-dash-cam-car-dvr-front-camera-or-rear-camera-night-vision-g-sensor",
    title: "2.4 Inch Full HD 1080p Dash Cam with Front and Rear",
    price: "39.00",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/a5b11e36-2506-4b80-a1e4-3caf942cb948.jpg?v=1740583181",
    category: "dash",
  },
  "anti-spy-hidden-camera-signal-detector": {
    handle: "anti-spy-hidden-camera-signal-detector",
    title: "Anti-Spy Hidden Camera Signal Detector",
    price: "25.00",
    image: "https://cdn.shopify.com/s/files/1/0908/9830/1233/files/2266994295197.jpg?v=1739756658",
    category: "detector",
  },
};

// Returns the product with a badge and blurb merged in. Handle must exist in PRODUCTS.
function pick(handle, badge, blurb) {
  const p = PRODUCTS[handle];
  if (!p) throw new Error(`fashionistasProducts: unknown handle ${handle}`);
  return { ...p, badge, blurb };
}

export { PRODUCTS, pick };

// Pre-curated editor roundups per HC page. Each roundup is 5-8 products with
// distinct editorial badges. Keep this the single source of truth so pages
// stay in sync and no duplicate hand-keyed arrays drift.
export const ROUNDUPS = {
  "best-hidden-cameras-2026": [
    pick("4k-mini-wifi-pinhole-hidden-camera", "Editor's Choice",
      "4K pinhole sensor in a disguise-friendly form factor. The sharpest image on our hidden camera shortlist."),
    pick("mini-hidden-nanny-cam-1080p", "Best Overall",
      "A versatile 1080p pick that blends into any shelf. WiFi app, motion alerts, night vision."),
    pick("pocket-pen-hd-hidden-camera", "Most Discreet",
      "A working pen that captures HD video. The textbook covert option for travel and short clips."),
    pick("dice-style-hidden-nanny-cam-1080p", "Best Design",
      "A prop-dice housing nobody suspects. Best hidden camera we tested for at-a-glance invisibility."),
    pick("night-vision-1080p-resolution-portable-mini-camera-1025333310", "Best Budget",
      "Under $20, portable, and low-light capable. The cheapest legitimate hidden cam that still records clean 1080p."),
    pick("wireless-1080p-indoor-security-camera", "Best Value",
      "Not technically disguised, but tiny enough to hide on a bookshelf. Two-way audio included."),
  ],
  "best-nanny-cam-2026": [
    pick("amcrest-1080p-nanny-pet-wifi-camera", "Editor's Choice",
      "The Amcrest is the nanny-cam benchmark. 1080p, pan-tilt, two-way audio, cloud backup optional."),
    pick("2k-pan-tilt-pet-baby-camera-with-smart-tracking", "Best Premium",
      "Sharpest 2K sensor in the roundup plus AI smart-tracking that follows a moving baby or pet."),
    pick("1080p-pan-tilt-zoom-indoor-pet-baby-monitor", "Best for Newborns",
      "Pan-tilt-zoom lets you sweep the whole crib from your phone. Clear night vision for naps."),
    pick("mini-wireless-wifi-nanny-cam-palm-size", "Most Discreet",
      "Palm-sized and wireless. Best for parents who want a second-opinion cam without alerting the sitter."),
    pick("dice-style-hidden-nanny-cam-1080p", "Best Disguise",
      "A prop-dice housing hides the camera in plain sight on a nightstand or toy shelf."),
    pick("mini-hidden-nanny-cam-1080p", "Best Budget",
      "Under $45 with 1080p, night vision, and motion alerts. The cheapest nanny cam we could endorse."),
  ],
  "best-doorbell-camera-2026": [
    pick("smart-wireless-video-doorbell-with-night-vision", "Editor's Choice",
      "Night-vision sensor plus a chime in one kit. Best all-around doorbell in the Fashionistas catalog."),
    pick("smart-wifi-video-doorbell-m7-with-remote-monitoring", "Best Smart Alerts",
      "M7 firmware pushes motion clips to your phone within two seconds of detection."),
    pick("battery-powered-wifi-video-doorbell", "Best for Apartments",
      "No wiring needed. Mounts with 3M strips and runs for months on a charge."),
    pick("wireless-wifi-video-doorbell-with-music-bell-full-hd-resolution-two-1508265658", "Best Value",
      "Ships with a plug-in chime so you do not need an echo device. HD video and two-way talk."),
    pick("smart-wireless-video-doorbell-with-night-vision", "Best Night Vision",
      "IR array still reads faces at the door in full dark. Strong pick for late-night deliveries."),
  ],
  "best-outdoor-security-camera-2026": [
    pick("wifi-surveillance-camera-4k-8mp-dual-lens-wireless-outdoor-security-ptz-ip-cameras-ai-human-detect-cctv-camera-4x-digital-zoom", "Editor's Choice",
      "4K dual-lens PTZ with AI human detect. The most capable outdoor camera we ship from Fashionistas."),
    pick("solar-powered-outdoor-wifi-camera-with-night-vision", "Best Battery Life",
      "Solar trickle-charge keeps it running forever. Ideal for driveways and sheds without power."),
    pick("1080p-ip66-outdoor-wifi-bullet-camera", "Best Premium",
      "IP66 bullet body survives heavy rain. Sharp 1080p clip to your NVR or phone."),
    pick("ip65-outdoor-wifi-camera-v380-pro", "Best Budget",
      "The V380 Pro app is free and the price is hard to beat for IP65 weather sealing."),
    pick("solar-powered-outdoor-wifi-camera-with-night-vision", "Best for Off-Grid",
      "No cables, no batteries to swap. The only fully wire-free outdoor pick in our catalog."),
  ],
  "best-hidden-camera-detector": [
    pick("anti-spy-hidden-camera-signal-detector", "Editor's Choice",
      "RF sweep plus lens-glint flashlight in one pocket tool. Finds pinhole cams at short range."),
    pick("anti-spy-hidden-camera-signal-detector", "Top Pick for Travel",
      "Small enough to live in a toiletry kit. Scan every Airbnb before you unpack."),
  ],
  "best-pet-camera-2026": [
    pick("2k-pan-tilt-pet-baby-camera-with-smart-tracking", "Editor's Choice",
      "Smart tracking follows your pet around the room. 2K video, two-way audio to settle a barking dog."),
    pick("1080p-pan-tilt-zoom-indoor-pet-baby-monitor", "Best Overall",
      "Pan-tilt-zoom from your phone so you can sweep the whole room. Ideal for cats and small dogs."),
    pick("amcrest-1080p-nanny-pet-wifi-camera", "Best for Dogs",
      "The Amcrest handles bark-detection alerts better than any cam we tested under $100."),
    pick("wireless-1080p-indoor-security-camera", "Best Budget",
      "Under $30 and good enough for quick check-ins while you are out for errands."),
    pick("mini-wireless-wifi-nanny-cam-palm-size", "Most Compact",
      "Palm-sized so you can place it anywhere a cat will not knock it off a shelf."),
  ],
  "best-car-dash-cam-2026": [
    pick("1080p-touch-screen-dashcam-with-carplay", "Editor's Choice",
      "Touchscreen plus CarPlay bridge means it doubles as your head-unit. Best premium dash cam in our catalog."),
    pick("4-inch-ips-dual-channel-starlight-night-vision-dashcam", "Best Night Vision",
      "Starlight sensor cuts through unlit roads. The sharpest after-dark footage we recorded."),
    pick("dual-lens-b6t-dashcam-12mp-170-view", "Best Dual Camera",
      "Front + rear dual 12MP with a 170 degree wide angle. Rideshare drivers buy this one."),
    pick("2-4-inch-full-hd-1080p-dash-cam-car-dvr-front-camera-or-rear-camera-night-vision-g-sensor", "Best Budget",
      "Under $40 with G-sensor auto-lock. The cheapest dash cam we endorse for daily commuters."),
  ],
  "best-hidden-cameras-airbnb": [
    pick("anti-spy-hidden-camera-signal-detector", "Editor's Choice",
      "Sweep the room in 60 seconds before you unpack. The safety tool every Airbnb guest should pack."),
    pick("pocket-pen-hd-hidden-camera", "Most Discreet",
      "If you want your OWN cam for valuables while you are out, this pen is the most portable option."),
    pick("4k-mini-wifi-pinhole-hidden-camera", "Best 4K Pick",
      "Share a space and want crisp evidence if things go wrong. 4K sensor in a pinhole body."),
    pick("mini-hidden-nanny-cam-1080p", "Best Budget",
      "A 1080p spare cam that fits in a carry-on pocket. Under $50 and easy to set up."),
  ],
  "nanny-cam": [
    pick("amcrest-1080p-nanny-pet-wifi-camera", "Editor's Choice",
      "The Amcrest is the nanny-cam benchmark for a reason. Full featured and reliable."),
    pick("mini-wireless-wifi-nanny-cam-palm-size", "Most Discreet",
      "Palm-sized, wireless, and hard to spot on a shelf."),
    pick("2k-pan-tilt-pet-baby-camera-with-smart-tracking", "Best Premium",
      "2K with AI tracking. Best image quality in the nanny-cam tier."),
    pick("1080p-pan-tilt-zoom-indoor-pet-baby-monitor", "Best for Newborns",
      "Pan-tilt-zoom full coverage of the crib area."),
    pick("mini-hidden-nanny-cam-1080p", "Best Budget",
      "Under $45. The cheapest nanny cam we trust."),
    pick("dice-style-hidden-nanny-cam-1080p", "Best Disguise",
      "A dice prop that nobody gives a second look."),
  ],
  "doorbell-cameras": [
    pick("smart-wireless-video-doorbell-with-night-vision", "Editor's Choice",
      "Night vision plus a wireless chime makes this the easiest upgrade from a dumb doorbell."),
    pick("smart-wifi-video-doorbell-m7-with-remote-monitoring", "Best Smart Alerts",
      "M7 pushes motion clips in under 2 seconds."),
    pick("battery-powered-wifi-video-doorbell", "Best for Apartments",
      "Mounts with 3M strips. No drilling, no wiring."),
    pick("wireless-wifi-video-doorbell-with-music-bell-full-hd-resolution-two-1508265658", "Best Value",
      "Ships with a plug-in music chime so you are not tethered to an app."),
  ],
  "outdoor-security-cameras": [
    pick("wifi-surveillance-camera-4k-8mp-dual-lens-wireless-outdoor-security-ptz-ip-cameras-ai-human-detect-cctv-camera-4x-digital-zoom", "Editor's Choice",
      "4K 8MP dual-lens PTZ. The most capable outdoor camera we stock."),
    pick("solar-powered-outdoor-wifi-camera-with-night-vision", "Best Battery Life",
      "Solar trickle keeps it online forever."),
    pick("1080p-ip66-outdoor-wifi-bullet-camera", "Most Weatherproof",
      "IP66 rated. Rain, snow, heat."),
    pick("ip65-outdoor-wifi-camera-v380-pro", "Best Budget",
      "V380 Pro app is free. Hard to beat at this price."),
  ],
  "indoor-security-cameras": [
    pick("2k-pan-tilt-pet-baby-camera-with-smart-tracking", "Editor's Choice",
      "Sharpest 2K indoor cam with AI smart tracking."),
    pick("1080p-pan-tilt-zoom-indoor-pet-baby-monitor", "Best Pan-Tilt",
      "Full room sweep from your phone."),
    pick("wireless-1080p-indoor-security-camera", "Best Budget",
      "Under $30 and good enough for most rooms."),
    pick("amcrest-1080p-nanny-pet-wifi-camera", "Staff Favorite",
      "Reliable, well-supported Amcrest app."),
  ],
  "pet-cameras": [
    pick("2k-pan-tilt-pet-baby-camera-with-smart-tracking", "Editor's Choice",
      "AI tracking follows your pet around the room."),
    pick("amcrest-1080p-nanny-pet-wifi-camera", "Best for Dogs",
      "Strong bark-detection alerts."),
    pick("1080p-pan-tilt-zoom-indoor-pet-baby-monitor", "Best Pan-Tilt",
      "Sweep the whole living room from your phone."),
    pick("mini-wireless-wifi-nanny-cam-palm-size", "Most Compact",
      "Small enough the cat will not knock it down."),
    pick("wireless-1080p-indoor-security-camera", "Best Budget",
      "Cheap enough to put one in every room."),
  ],
  "trail-cameras": [
    pick("solar-powered-outdoor-wifi-camera-with-night-vision", "Editor's Choice",
      "Solar-powered is the game-changer for trail setups. No battery swaps."),
    pick("ip65-outdoor-wifi-camera-v380-pro", "Best Budget",
      "IP65 weather sealing for woods or yard."),
    pick("1080p-ip66-outdoor-wifi-bullet-camera", "Most Weatherproof",
      "IP66 bullet survives storms and heat."),
    pick("wifi-surveillance-camera-4k-8mp-dual-lens-wireless-outdoor-security-ptz-ip-cameras-ai-human-detect-cctv-camera-4x-digital-zoom", "Best 4K Pick",
      "4K dual-lens PTZ sees farther than most trail rigs."),
  ],
  "body-cameras": [
    pick("pocket-pen-hd-hidden-camera", "Editor's Choice",
      "A pen-form factor is the most wearable option in our catalog."),
    pick("night-vision-1080p-resolution-portable-mini-camera-1025333310", "Most Portable",
      "Pocket-size with night vision. Clips anywhere."),
    pick("4k-mini-wifi-pinhole-hidden-camera", "Best 4K Pick",
      "Sharpest sensor we stock in a body-wearable size."),
  ],
  "car-cameras": [
    pick("1080p-touch-screen-dashcam-with-carplay", "Editor's Choice",
      "Touchscreen plus CarPlay makes this a legit in-dash upgrade."),
    pick("dual-lens-b6t-dashcam-12mp-170-view", "Best Dual Camera",
      "12MP front + rear with 170 degree wide angle."),
    pick("4-inch-ips-dual-channel-starlight-night-vision-dashcam", "Best Night Vision",
      "Starlight sensor sees clearly on unlit roads."),
    pick("2-4-inch-full-hd-1080p-dash-cam-car-dvr-front-camera-or-rear-camera-night-vision-g-sensor", "Best Budget",
      "Under $40 with G-sensor auto-lock."),
  ],
  "mini-spy-cameras": [
    pick("4k-mini-wifi-pinhole-hidden-camera", "Editor's Choice",
      "4K pinhole in a truly miniature body. Top pick for discreet evidence."),
    pick("pocket-pen-hd-hidden-camera", "Most Discreet",
      "Working pen + HD camera. Nobody looks twice."),
    pick("night-vision-1080p-resolution-portable-mini-camera-1025333310", "Best Budget",
      "Under $20 and still 1080p with night vision."),
    pick("mini-hidden-nanny-cam-1080p", "Staff Favorite",
      "Tiny form factor, solid feature set."),
    pick("dice-style-hidden-nanny-cam-1080p", "Best Disguise",
      "A dice prop that nobody suspects."),
  ],
  "spy-cameras": [
    pick("4k-mini-wifi-pinhole-hidden-camera", "Editor's Choice",
      "4K pinhole in a miniature body. Sharpest spy-cam sensor we stock."),
    pick("pocket-pen-hd-hidden-camera", "Most Discreet",
      "Pen form factor, HD capture."),
    pick("dice-style-hidden-nanny-cam-1080p", "Best Disguise",
      "Dice prop hides in plain sight."),
    pick("mini-hidden-nanny-cam-1080p", "Best Budget",
      "Under $45 for 1080p and WiFi."),
    pick("anti-spy-hidden-camera-signal-detector", "Essential Add-On",
      "The counter-tool. Every spy-cam owner should also know how to find one."),
  ],
  "wireless-security-cameras": [
    pick("solar-powered-outdoor-wifi-camera-with-night-vision", "Editor's Choice",
      "Solar keeps it online without cables. Most truly wireless camera we stock."),
    pick("battery-powered-wifi-video-doorbell", "Best Doorbell",
      "No wiring needed. Mounts with 3M strips."),
    pick("ip65-outdoor-wifi-camera-v380-pro", "Best Outdoor Budget",
      "IP65 weather sealing, WiFi only, cheap."),
    pick("mini-wireless-wifi-nanny-cam-palm-size", "Most Compact",
      "Palm-sized and fully wireless."),
    pick("2k-pan-tilt-pet-baby-camera-with-smart-tracking", "Best Indoor",
      "2K wireless with AI tracking."),
  ],
};
